@startuml
skinparam componentStyle uml2
left to right direction

interface "BLE Profile" [[https://github.com/motorica-org/telemetry-docs/wiki/BLE-Profile]]

package Hardware {
    component MCU
    component BLE

    package Sensors {
        [FlexSensor] -> [MCU]
    }

    [MCU] -> [BLE]
    [BLE] - (BLE Profile)

    note bottom of [MCU]: integrated w/BLE
    note bottom of [BLE]: nrf51822
}

package Mobile {
    (BLE Profile) -> [Aggregator]
    [Aggregator] -> [Monsik]
}

package Server {
    package Storage {
        [Aggregator] -> [RawCache]
        [RawCache] -> [ParsedStorage]
    }
    package Analytics {
        [ParsedStorage] -> [QueryEngine]
        [QueryEngine] -> [Visualizer]
        [QueryEngine] -> [Alerting]
    }

    note bottom of RawCache: Matrix.org
    note bottom of ParsedStorage: InfluxDB
    note bottom of QueryEngine: InfluxDB
    note bottom of Visualizer: Grafana
    note bottom of Alerting: Kapacitor
}

package Actors {
    actor Child
    actor Parent
    actor Analytic

    Child <- [Monsik]

    Parent <- [Visualizer]
    Parent <- [Alerting]

    Analytic <-u- [QueryEngine]
    Analytic <-u- [Visualizer]
}
@enduml
