@startuml
skinparam componentStyle uml2

package Hardware {
    component MCU
    component BLE

    package Sensors {
        [FlexSensor] -> [MCU]
    }

    [MCU] -> [BLE]

    note bottom of [MCU]: Teensy 3.2
    note bottom of [BLE]: nrf51822
}

package Mobile {
    [BLE] -> [Aggregator]
    [Aggregator] -> [Monsik]
}

package Server {
    package Storage {
        [Aggregator] -> [RawCache]
        [RawCache] -> [Storage]
    }
    package Analytics {
        [Storage] -> [QueryEngine]
        [QueryEngine] -> [Visualizator]
    }
}

package Actors {
    actor Child
    actor Parent
    actor Analytic

    Child <- [Monsik]

    Parent <- [Visualizator]

    Analytic <- [QueryEngine]
    Analytic <- [Visualizator]
}

@enduml
